//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickMathsMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class CMQuiz
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "*This field can't be empty")]
        [DisplayName("Correct Answer:")]
        public Nullable<int> CorrectAnswer { get; set; }
        [Required(ErrorMessage = "*This field can't be empty")]
        [DisplayName("Points:")]
        public Nullable<int> Points { get; set; }
        [Required(ErrorMessage = "*This field can't be empty")]
        public string QuizImg { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImgExample { get; set; }

        public CMQuiz()
        {
            QuizImg = "~/AppFile/Img/plus-button.png";
        }
    }
}
